/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  AuditionPlayer as AuditionPlayer
} from './components/audition-player/audition-player';

declare global {
  interface HTMLAuditionPlayerElement extends AuditionPlayer, HTMLElement {
  }
  var HTMLAuditionPlayerElement: {
    prototype: HTMLAuditionPlayerElement;
    new (): HTMLAuditionPlayerElement;
  };
  interface HTMLElementTagNameMap {
    "audition-player": HTMLAuditionPlayerElement;
  }
  interface ElementTagNameMap {
    "audition-player": HTMLAuditionPlayerElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "audition-player": JSXElements.AuditionPlayerAttributes;
    }
  }
  namespace JSXElements {
    export interface AuditionPlayerAttributes extends HTMLAttributes {
      src?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
